# Generated by Django 4.1.4 on 2022-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='model_pics')),
                ('description', models.TextField()),
            ],
        ),
    ]
